apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-kubernetes
  name: spring-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-kubernetes
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-kubernetes
    spec:
      containers:
      - image: csfulop/spring_kubernetes:v1
        name: spring-kubernetes-jnpjk
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-kubernetes
  name: spring-kubernetes
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-kubernetes
  type: NodePort
status:
  loadBalancer: {}
